name: Create PRs from Release to Main

on:
  workflow_dispatch:

jobs:
  create_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Create PR in first repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/abhishek-7901/r1/pulls" \
            -d '{
              "title": "Merge release into main",
              "head": "release",
              "base": "main",
              "body": "Automated merge of release branch into main branch."
            }')
          echo "PR Response: $pr_response"

      - name: Create PR in second repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pr_response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/abhishek-7901/r2/pulls"\
            -d '{
              "title": "Merge release into main",
              "head": "release",
              "base": "main",
              "body": "Automated merge of release branch into main branch."
            }')
          echo "PR Response: $pr_response"
